/** @type {import('tailwindcss').Config} */
import nativewindPreset from "nativewind/preset";

export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "../../packages/ui/src/**/*.{js,ts,jsx,tsx}",
  ],
  important: "html",
  presets: [nativewindPreset],
  theme: {
    extend: {
      colors: {
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0edec",
        "surface-container-high": "#ebe7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#584048",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        outline: "#8c7078",
        "outline-variant": "#dfbec7",
        "surface-tint": "#b70b67",
        primary: "#af0062",
        "on-primary": "#ffffff",
        "primary-container": "#d12a7b",
        "on-primary-container": "#fff5f6",
        "inverse-primary": "#ffb0ca",
        secondary: "#1259c3",
        "on-secondary": "#ffffff",
        "secondary-container": "#5e93ff",
        "on-secondary-container": "#002b69",
        tertiary: "#705d00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#c9a900",
        "on-tertiary-container": "#4c3f00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffd9e3",
        "primary-fixed-dim": "#ffb0ca",
        "on-primary-fixed": "#3e001f",
        "on-primary-fixed-variant": "#8d004e",
        "secondary-fixed": "#d9e2ff",
        "secondary-fixed-dim": "#afc6ff",
        "on-secondary-fixed": "#001944",
        "on-secondary-fixed-variant": "#004299",
        "tertiary-fixed": "#ffe16d",
        "tertiary-fixed-dim": "#e9c400",
        "on-tertiary-fixed": "#221b00",
        "on-tertiary-fixed-variant": "#544600",
        background: "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface-variant": "#e5e2e1",
      },
      fontFamily: {
        display: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        headline: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        body: ["var(--font-be-vietnam)", "Be Vietnam Pro", "sans-serif"],
        label: ["var(--font-be-vietnam)", "Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px" }],
        "body-md": ["16px", { lineHeight: "24px" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.5rem",
        DEFAULT: "1rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-margin-mobile": "20px",
        "container-margin-desktop": "40px",
        gutter: "16px",
      },
      boxShadow: {
        card: "0 2px 8px 0 rgba(175, 0, 98, 0.15)",
        fab: "0 4px 16px 0 rgba(175, 0, 98, 0.35)",
        modal: "0 8px 40px 0 rgba(0, 0, 0, 0.2)",
      },
    },
  },
  plugins: [],
};
