/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "../../packages/ui/src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0edec",
        "surface-container-high": "#ebe7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#584048",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        outline: "#8c7078",
        "outline-variant": "#dfbec7",
        "surface-tint": "#b70b67",
        primary: "#af0062",
        "on-primary": "#ffffff",
        "primary-container": "#d12a7b",
        "on-primary-container": "#fff5f6",
        "inverse-primary": "#ffb0ca",
        secondary: "#1259c3",
        "on-secondary": "#ffffff",
        "secondary-container": "#5e93ff",
        "on-secondary-container": "#002b69",
        tertiary: "#705d00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#c9a900",
        "on-tertiary-container": "#4c3f00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffd9e3",
        "primary-fixed-dim": "#ffb0ca",
        "on-primary-fixed": "#3e001f",
        "on-primary-fixed-variant": "#8d004e",
        "secondary-fixed": "#d9e2ff",
        "secondary-fixed-dim": "#afc6ff",
        "on-secondary-fixed": "#001944",
        "on-secondary-fixed-variant": "#004299",
        "tertiary-fixed": "#ffe16d",
        "tertiary-fixed-dim": "#e9c400",
        "on-tertiary-fixed": "#221b00",
        "on-tertiary-fixed-variant": "#544600",
        background: "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface-variant": "#e5e2e1",
      },
      fontFamily: {
        display: "PlusJakartaSans",
        headline: "PlusJakartaSans",
        body: "BeVietnamPro",
        label: "BeVietnamPro",
      },
      fontSize: {
        display: 48,
        "headline-lg": 32,
        "headline-lg-mobile": 28,
        "headline-md": 24,
        "body-lg": 18,
        "body-md": 16,
        "label-md": 14,
        "label-sm": 12,
      },
      borderRadius: {
        sm: 8,
        DEFAULT: 16,
        md: 24,
        lg: 32,
        xl: 48,
        full: 9999,
      },
      spacing: {
        "stack-sm": 8,
        "stack-md": 16,
        "stack-lg": 32,
        "container-margin-mobile": 20,
        "container-margin-desktop": 40,
        gutter: 16,
      },
    },
  },
  plugins: [],
};
